#!/bin/bash
imagename="baymax"
docker_namespace="dontrebootme"
if [ $# -eq 0 ];then
 tagver="latest"
else
 tagver="${1}"
fi
echo "Now building: ${imagename}:${tagver}"
docker build --rm=true --no-cache=true --pull=true -t ${docker_namespace}/${imagename}:"${tagver}" .
docker push ${docker_namespace}/${imagename}:"${tagver}"
